import type { Metadata } from "next";
import "./globals.css";
import { DialogProvider, SpinnerProvider } from "./components";
import { TRPCReactProvider } from "./lib/trpc/client";

export const metadata: Metadata = {
  title: "MyCloud 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DialogProvider>
          <TRPCReactProvider>
            <SpinnerProvider>
              {children}
            </SpinnerProvider>
            </TRPCReactProvider>
          </DialogProvider>
      </body>
    </html>
  );
}
