import type { Metadata } from "next";
import "./globals.css";
import { DialogProvider, SpinnerProvider } from "./components";
import { TRPCReactProvider } from "./lib/trpc/client";

export const metadata: Metadata = {
  title: "MyCloud 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
      <script dangerouslySetInnerHTML={{
          __html: `
            const theme = localStorage.getItem('theme');
            const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;

            if (theme === 'dark' || (!theme && prefersDark)) {
              document.documentElement.classList.add('dark');
            }
          `
        }} />
      </head>
      <body>
        <DialogProvider>
          <TRPCReactProvider>
            <SpinnerProvider>
              {children}
            </SpinnerProvider>
            </TRPCReactProvider>
          </DialogProvider>
      </body>
    </html>
  );
}
