import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./components/AuthProvider";
import { DialogProvider, QueryProvider } from "./components";

export const metadata: Metadata = {
  title: "MyCloud 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <DialogProvider>
            <AuthProvider>
                {children}
              </AuthProvider>
            </DialogProvider>
          </QueryProvider>
      </body>
    </html>
  );
}
